version: '3.7'

services:

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myPassword
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data/:/var/lib/mysql/
      - ./mysql/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./logs/mysql:/var/log/mysql

  tomcat:
    image: tomcat:7.0.96
    restart: always
    ports:
      - 8080:8080
      - 8009:8009
    volumes:
      - ./tomcat/webapps/myProject.war:/usr/local/tomcat/webapps/myProject.war
      - ./tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./logs/tomcat/:/usr/local/tomcat/logs/
    links:
      - mysql

  nginx:
    image: nginx:1.17
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/:/var/log/nginx/
    links:
      - tomcat

  

